[package]
name = "pg2sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
polars = { version = "0.49", default-features = false }
postgres = "0.19.10"
rusqlite = "0.37.0"
serde = "1.0.219"
serde_json = "1.0.141"
